apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
spec:
  replicas: 2
  selector: # [Must] Deploymentによって対象となるPodのラベルを指定する。
    matchLabels:
      app: counter-app # [Must] Podのlabelsに指定したラベルを記述する。
  template: # [Must] Podのテンプレート
    metadata: # [Must] デプロイするPodのメタデータ
      labels:
        app: counter-app # [Must] Podのラベル名
    spec: # [Must] デプロイするPodの詳細な情報を記述する。
      containers:
        - name: counter-app
          image: busybox
          command:
            [
              "/bin/sh",
              "-c",
              "echo 'Start'; CNT=0; while [ $CNT -lt 10 ]; do echo 'Number is: '$CNT; CNT=$(( CNT + 1 ));done; echo 'End'; sleep 1800",
            ]
          resources: # [Option]
            limits: # [Option] CPUやメモリなどのリソースの上限値
              memory: 512Mi
              cpu: "1"
            requests: # [Option] CPUやメモリなどのリソースの最低値
              memory: 256Mi
              cpu: "0.2"
