version: "3.9"
services:
  rabbitmq-receiver:
    container_name: rabbitmq-receiver
    image: rabbitmq-receiver:latest
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
    environment:
      - AMQP_URL=amqp://user:PASSWORD@rabbitmq-headless.default.svc.cluster.local:5672
