apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  template:
    metadata:
      name: hello-v3
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
  # Revision毎のルーティング割合の設定
  traffic:
    - revisionName: hello-v3
      percent: 50
    - revisionName: hello-v2
      percent: 30
    - revisionName: hello-v1
      percent: 20
