apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hpa-app
  template:
    metadata:
      name: hpa-app
      labels:
        app: hpa-app
    spec:
      containers:
        - name: hpa-app
          image: busybox:latest
          command: ["dd", "if=/dev/zero", "of=/dev/null"] # CPUを100%使うように指定
          resources:
            limits: # PodのCPU/メモリ上限値の設定
              memory: 256Mi
              cpu: "0.2"
            requests: # PodのCPU/メモリ下限値の設定
              memory: 128Mi
              cpu: "0.1"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-test
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-app # オートスケーリング対象のリソース名
  minReplicas: 1 # Pod数の最小値
  maxReplicas: 8 # Pod数の最大値
  metrics: # スケーリングの条件
    - type: Resource
      resource:
        name: cpu
        # Podの平均CPU稼働率が50%を超えたらスケールアウト
        target:
          type: Utilization
          averageUtilization: 50
