apiVersion: v1
kind: Service
metadata:
  name: python-fastapi
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: python-fastapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-fastapi
  template:
    metadata:
      labels:
        app: python-fastapi
    spec:
      containers:
        - name: python-fastapi
          image: python-fastapi-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
