apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: knative-cluster # EKSクラスター名
  region: ap-northeast-1 # リージョン
  version: "1.27"

nodeGroups:
  - name: knative-cluster-ng # ノードグループ名
    instanceType: t3.medium # EC2インスタンスタイプ
    desiredCapacity: 2 # ワーカーノード(EC2インスタンス)数
    minSize: 2 # 最小ワーカーノード数
    maxSize: 2 # 最大ワーカーノード数
    volumeSize: 20 # EBSボリュームサイズ(Default:8GB)
