apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  type: LoadBalancer # アプリを外部に公開
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 4
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd:latest # コンテナイメージの指定
          ports:
            - containerPort: 80 # コンテナの公開ポート番号
          resources:
            limits: # PodのCPU/メモリ上限値の設定
              memory: 512Mi
              cpu: "1"
            requests: # PodのCPU/メモリ下限値の設定
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apache-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache
  minReplicas: 1 # Pod数の最小値
  maxReplicas: 8 # Pod数の最大値
  metrics: # スケーリングの条件
    - type: Resource
      resource:
        name: cpu
        # Podの平均CPU稼働率が80%を超えたらスケールアウト
        target:
          type: Utilization
          averageUtilization: 80
